name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Clone the repo
        run: |
          west init -m https://github.com/kaizoku-oh/zephyr-app-workspace --mr $BRANCH_NAME workspace
          cd workspace
          west update

      - name: Build bootloader
        working-directory: workspace
        run: |
          west build deps/bootloader/mcuboot/boot/zephyr -d deps/bootloader/mcuboot/boot/zephyr/build -b nucleo_f767zi

      - name: Build application
        working-directory: workspace
        run: |
          west build app -d app/build -b nucleo_f767zi
