name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Clone the repo
        run: |
          west init -m https://github.com/kaizoku-oh/stm32-zephyr-app --mr dev workspace
          cd workspace
          west update

      - name: Build firmware
        working-directory: workspace
        run: |
          west build app -d app/build -b nucleo_f767zi
